#!/bin/sh /etc/rc.common
START=20
USE_PROCD=1
PROG=/usr/sbin/ssd1306
THEME=$(uci get ssd1306.theme)
SCRIPT_PATH=$THEME/scripts
CONFIG=$THEME/conf.json

start_service(){
	if [ -f "$THEME/init.sh" ]; then
	bash $THEME/init.sh
	fi
	if [ -d "$SCRIPT_PATH" ]; then
		while read line; do
			procd_open_instance $line
			procd_set_param command bash $SCRIPT_PATH/$line
			procd_set_param stdout 1
			procd_close_instance
		done < $SCRIPT_PATH/services.list
	fi
	[ -f "$CONFIG" ] || CONFIG=/usr/etc/oled/fallback.json 
	procd_open_instance oled_main
	procd_set_param command $PROG $CONFIG
	proce_set_param stdout 1
	procd_close_instance
}

stop_service(){
	$PROG stop
}
